### ISSUE TITLE
1

### ISSUE THREAD

**Issue by gstsgy** [ChrisYang755/freevpn-ss.tk#2]

**Comment by zxfd** [comment]
服务器进不去




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"追寻"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月10日(星期二) 下午2:43
收件人:&nbsp;"ChrisYang755/freevpn-ss.tk"<freevpn-ss.tk@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [ChrisYang755/freevpn-ss.tk] 1 (#2)




Closed #2.
